[phases.setup]
apt_pkgs = ["libfreetype6-dev", "libjpeg62-turbo-dev", "libpng-dev"]

[phases.build]
cmds = [
  "docker-php-ext-configure gd --with-freetype --with-jpeg",
  "docker-php-ext-install gd",
  "composer install --optimize-autoloader --no-scripts --no-interaction"
]
