name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Rsync files to EC2
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          rsync -avz --delete \
          --exclude 'web/sites/default/files' \
          --exclude '.git' \
          --exclude '.env' \
          --exclude 'node_modules' \
          --exclude 'vendor' \
          -e "ssh -i ~/.ssh/id_rsa" \
          ./ ubuntu@${{ secrets.EC2_HOST }}:/var/www/mysite

      - name: Run deployment commands on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/mysite

            # Install composer deps on server
            composer install --no-dev --optimize-autoloader

            # Ensure writable dirs exist
            sudo mkdir -p web/sites/default/files/{css,js,php,temp}

            # File/folder permissions
            sudo chown -R www-data:www-data web/sites/default/files
            sudo find web/sites/default/files -type d -exec chmod 775 {} \;
            sudo find web/sites/default/files -type f -exec chmod 664 {} \;

            # Clean caches
            sudo -u www-data rm -rf web/sites/default/files/css/* web/sites/default/files/js/* || true

            # Drupal tasks
            sudo -u www-data vendor/bin/drush updatedb -y
            if [ -d config/sync ] && [ "$(ls -A config/sync)" ]; then
              sudo -u www-data vendor/bin/drush config:import -y
            fi
            sudo -u www-data vendor/bin/drush cache:rebuild -y
