name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Rsync files to EC2
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          rsync -avz --delete \
          --exclude 'web/sites/default/files' \
          --exclude '.git' \
          --exclude '.env' \
          --exclude 'node_modules' \
          -e "ssh -i ~/.ssh/id_rsa" \
          ./ ubuntu@${{ secrets.EC2_HOST }}:/var/www/mysite

      - name: Run deployment commands on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /var/www/mysite

            # Install backend deps
            composer install --no-dev --optimize-autoloader

            # Ensure file & temp directories exist with correct perms
            sudo mkdir -p web/sites/default/files/css \
                         web/sites/default/files/js \
                         web/sites/default/files/php \
                         web/sites/default/files/temp
            sudo chown -R www-data:www-data web/sites/default/files
            sudo chmod -R 775 web/sites/default/files

            # Run DB updates
            vendor/bin/drush updatedb -y

            # Run config import ONLY if sync dir exists and has YAML files
            if [ -d "web/sites/default/files/sync" ] && [ "$(ls -1 web/sites/default/files/sync/*.yml 2>/dev/null | wc -l)" -gt 0 ]; then
              echo "Config sync directory found with content, running config import..."
              vendor/bin/drush config:import -y
            else
              echo "No config sync directory or empty, skipping config import."
            fi

            # Clear caches
            vendor/bin/drush cache:rebuild -y
