name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare EC2 directories
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Create target directory with proper permissions
            sudo mkdir -p /var/www/mysite
            sudo chown -R ubuntu:ubuntu /var/www/mysite
            sudo chmod -R 755 /var/www/mysite

            # Ensure web/sites directory structure exists with proper permissions
            sudo mkdir -p /var/www/mysite/web/sites/default
            sudo mkdir -p /var/www/mysite/web/sites/japachronicles.xyz
            sudo chown -R ubuntu:ubuntu /var/www/mysite/web/sites
            sudo chmod -R 755 /var/www/mysite/web/sites

      - name: Rsync project files to EC2
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          rsync -avz --delete \
          --exclude 'web/sites/*/files' \
          --exclude 'web/sites/*/settings.php' \
          --exclude 'web/sites/*/*.settings.*.php' \
          --exclude 'web/sites/*/*.yml' \
          --exclude 'vendor' \
          --exclude 'web/core' \
          --exclude '.git' \
          --exclude '.env' \
          --exclude 'node_modules' \
          -e "ssh -i ~/.ssh/id_rsa" \
          ./ ubuntu@${{ secrets.EC2_HOST }}:/var/www/mysite

      - name: Run deployment commands on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/mysite

            # Install dependencies (Drupal core + contrib modules + vendor libs)
            composer install --no-dev --optimize-autoloader --prefer-dist --no-progress

            # Default site
            sudo mkdir -p web/sites/default/files/{css,js,php,temp}
            sudo mkdir -p web/sites/default/config/sync
            sudo cp -n web/sites/default/default.settings.php web/sites/default/settings.php

            # Japachronicles site
            sudo mkdir -p web/sites/japachronicles.xyz/files/{css,js,php,temp}
            sudo mkdir -p web/sites/japachronicles.xyz/config/sync
            sudo cp -n web/sites/default/default.settings.php web/sites/japachronicles.xyz/settings.php

            sudo chown -R www-data:www-data web/sites
            sudo find web/sites -type d -exec chmod 775 {} \;
            sudo find web/sites -type f -exec chmod 664 {} \;

            sudo -u www-data rm -rf web/sites/default/files/css/* web/sites/default/files/js/* || true
            sudo -u www-data rm -rf web/sites/japachronicles.xyz/files/css/* web/sites/japachronicles.xyz/files/js/* || true

            # Default site
            sudo -u www-data vendor/bin/drush -l penzest.dev updatedb -y
            if [ -d web/sites/default/config/sync ] && [ "$(ls -A web/sites/default/config/sync)" ]; then
              sudo -u www-data vendor/bin/drush -l penzest.dev config:import -y
            fi
            sudo -u www-data vendor/bin/drush -l penzest.dev cache:rebuild -y

            # Japachronicles site
            sudo -u www-data vendor/bin/drush -l japachronicles.xyz updatedb -y
            if [ -d web/sites/japachronicles.xyz/config/sync ] && [ "$(ls -A web/sites/japachronicles.xyz/config/sync)" ]; then
              sudo -u www-data vendor/bin/drush -l japachronicles.xyz config:import -y
            fi
            sudo -u www-data vendor/bin/drush -l japachronicles.xyz cache:rebuild -y
