name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Rsync files to EC2
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          rsync -avz --delete \
          --exclude 'web/sites/default/files' \
          --exclude '.git' \
          --exclude '.env' \
          --exclude 'node_modules' \
          -e "ssh -i ~/.ssh/id_rsa" \
          ./ ubuntu@${{ secrets.EC2_HOST }}:/var/www/mysite

      - name: Run deployment commands on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/mysite
            composer install --no-dev --optimize-autoloader
            sudo chown -R www-data:www-data web/sites/default/files
            vendor/bin/drush updatedb -y
            vendor/bin/drush config:import -y
            vendor/bin/drush cache:rebuild -y
            vendor/bin/drush cr
            vendor/bin/drush theme:compile -y || true  # optional if using theme build tools
